In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd

file_path = '/content/drive/MyDrive/AIML/ML_Practise_Dataset/employee_promotion.csv'
df = pd.read_csv(file_path)
display(df.head())

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,City,Promotion
0,28,132612,9,2,1,Data Engineer,High School,Seattle,Got Promotion
1,41,116641,8,4,3,Data Scientist,Master's,Chicago,No Promotion
2,36,113811,11,1,6,Web developer,PhD,Chicago,Got Promotion
3,32,102160,2,2,6,Data Engineer,High School,Austin,No Promotion
4,29,101313,7,4,7,Product Manager,Bachelor's,San Francisco,No Promotion

In [3]:
df.shape

(5000, 9)

In [5]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [13]:
from sklearn.preprocessing import LabelEncoder

#Copying the original dataset
df_encoded = df.copy()

#Label Encoding for Promotion (mostly for target variable)
label_encoder = LabelEncoder()
df_encoded['Promotion_Enc'] = label_encoder.fit_transform(df_encoded['Promotion'])

display(df_encoded)

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,City,Promotion,Promotion_Enc
0,28,132612,9,2,1,Data Engineer,High School,Seattle,Got Promotion,0
1,41,116641,8,4,3,Data Scientist,Master's,Chicago,No Promotion,1
2,36,113811,11,1,6,Web developer,PhD,Chicago,Got Promotion,0
3,32,102160,2,2,6,Data Engineer,High School,Austin,No Promotion,1
4,29,101313,7,4,7,Product Manager,Bachelor's,San Francisco,No Promotion,1
...,...,...,...,...,...,...,...,...,...,...
4995,38,127658,3,1,10,Data Scientist,High School,Austin,No Promotion,1
4996,39,84840,9,3,4,Data Scientist,Bachelor's,Chicago,Got Promotion,0
4997,34,81007,4,0,4,Web developer,PhD,Austin,Got Promotion,0
4998,41,106947,12,2,10,Data Scientist,Bachelor's,Seattle,No Promotion,1
4999,41,143220,12,3,4,Product Manager,High School,New York,No Promotion,1